### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by alexbarbato** [vito/booklit#22]
This is a question more than a bug report, but would the windows binary still work with the addition of "plugin" package?

Minimally, I wouldn't expect the "--plugin" flag to work on windows, right?

Just food for thought. I almost opened a PR to remove the windows binary creation, but I decided against it as I actually don't know how the binary compilation step works for these go packages and if booklit is no longer windows compatible at all, just partially, or completely unimpaired.

Thanks!

**Comment by vito** [comment]
I'm pretty sure it works until you try to use `--plugin`. I just tried it though and some basic things are broken, like dealing with Windows-style line endings. Woops!

I might have to just back out the change to how plugins work, or try to find a way to fallback on the old method. I was kind of hoping Windows support for the `plugin` package would arrive soon, but it looks like no one has contributed it to Go yet: https://github.com/golang/go/issues/19282#issuecomment-480052119

**Comment by vito** [comment]
I've fixed Windows-style line endings in the parser and rolled back the use of the `plugin` package. Seems like everything works now!
